# Generated by Django 3.2.9 on 2022-01-02 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0010_auto_20220102_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='task_id',
            new_name='event_id',
        ),
        migrations.AlterField(
            model_name='userlog',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 17, 33, 18, 648887)),
        ),
    ]
